### ISSUE TITLE
Including things outside the Webpack output path

### ISSUE THREAD

**Issue by poltak** [erikdesjardins/zip-webpack-plugin#26]
Hi there. Apologies if this is simple; I can't seem to find out how to do it from reading the docs/previous issues.

I have a working plugin instance producing a zip of my built files (in `proj/extension/` subdir - webpack's output), but I also want to set up another plugin instance to produce a zip of the source files (in `proj/src/` subdir). 

I've tried things like setting the `include` option to a string like `'../src/**/*'` and `'../src/'` however this results in an empty zip. **Is there a way to include files outside the webpack output dir?**

<br />

For reference, my working plugin that zips the built assets looks like this:
```js
new ZipPlugin({
  path: '../dist',
  filename: 'extension.zip',
  exclude: [/\.map/],
})
```

This project is a Chrome and FF compatible web extension and Mozilla [requires us to send zipped-up source code](https://developer.mozilla.org/en-US/Add-ons/Source_Code_Submission) as part of the FF add-on submission for later review. Worst-case I'll just automate it outside of the scope of webpack, but would be nice to do all needed packaging together (and I'm probably just missing something small).

Thanks for taking the time to read.

**Comment by erikdesjardins** [comment]
Right now loading files from outside the webpack build/emit process is out of scope for this plugin, so you have a few options:

- do it outside of webpack, as you mention (there might be a webpack plugin to run custom code after a build)
- load the files somehow with file-loader (or another loader, since you probably can't load dirs with file-loader)
- load the files with copy-webpack-plugin (both it and this plugin need to run during the emit phase, so ordering might matter unfortunately, or they might not work together)

My main concern with adding it is: right now this plugin is relatively simple, because webpack handles the file loading, dependency tracking for watch mode, etc., and this plugin just reads the assets; but to load additional files that has to be done manually (see, e.g., [copy-webpack-plugin source](https://github.com/webpack-contrib/copy-webpack-plugin/tree/c779a3026baee4b239db0e8b3fc3900ccbe067d4/src)).

Incidentally, I also contribute to a browser extension ([honestbleeps/Reddit-Enhancement-Suite](https://github.com/honestbleeps/Reddit-Enhancement-Suite)), but we don't submit the source code to Mozilla. I believe we link to the repo instead.

**Comment by poltak** [comment]
Thanks for your detailed reply and suggestions @erikdesjardins! First one seems to be the simplest for now, so I found the very simple [`post-compile-webpack-plugin`](https://github.com/EGOIST/post-compile-webpack-plugin) which affords running a custom callback in which I can just do a `child_process.exec` call to zip things manually for now.

> Incidentally, I also contribute to a browser extension (honestbleeps/Reddit-Enhancement-Suite), but we don't submit the source code to Mozilla. I believe we link to the repo instead.

It would be great to not have to worry about this and just send a link. I don't handle submissions, but I'll have a talk to the guy who does :) Thanks for the heads-up!
